### ISSUE TITLE
Reuse values for fields with matching IDs

### ISSUE THREAD

**Issue by vilav** [guillaumepotier/Garlic.js#100]
hi there

Just wondering if the values stored for a form on one page can be re-purposed for a form on another page of the same website if the ID / class of both forms can be matched? Is there a demo technique / some example of this being accomplished?

Thanks

**Comment by guillaumepotier** [comment]
Hi there,

Nope, that won't be an easy thing to do. Garlic does not rely on form/imputs names or ids, but rather on #forms and #elements in the page and their position/hierarchy inside.

If you want to do so, you'll have to implement your own localStorage/cookie logic.

Best
