### ISSUE TITLE
Does not reset checkbox/radio state on persisted view

### ISSUE THREAD

**Issue by Dodger77** [guillaumepotier/Garlic.js#101]
On persisted view resetting of checkboxes or radios does not work.

Testing is possible in simple form on http://garlicjs.org/

**Comment by artdijk** [comment]
The library is great but this is a serious issue. Are you working on it?
Thanks

**Comment by guillaumepotier** [comment]
Okay found the issue. I'm releasing a fix today.

**Comment by guillaumepotier** [comment]
Ok should be ok with latest 1.3.0

Best

**Comment by artdijk** [comment]
Thanks !

 

Van: Guillaume Potier [mailto:notifications@github.com] 
Verzonden: maandag 27 maart 2017 10:44
Aan: guillaumepotier/Garlic.js <Garlic.js@noreply.github.com>
CC: artdijk <artdijk@xs4all.nl>; Comment <comment@noreply.github.com>
Onderwerp: Re: [guillaumepotier/Garlic.js] Does not reset checkbox/radio state on persisted view (#101)

 

Ok should be ok with latest 1.3.0

Best
