### ISSUE TITLE
Form emptied on submit, resulting in invalid form

### ISSUE THREAD

**Issue by rvanlaak** [guillaumepotier/Garlic.js#106]
@guillaumepotier while testing #105 on `staging`, another form we use Garlic on gets emptied / destroyed before submit. As a result of that no data is sent, and the form validation does not pass as the CQRF token also is cleared.

Narrowed this down to comparing 1.2.4 to 1.3.0, on which the bug occurs (so is not specific to PR #105 ): https://github.com/guillaumepotier/Garlic.js/compare/1.2.4...master

The form initialization used to be like this:

```js
$(function() {
    $('#orderInfoForm').garlic({
        excluded: '[data-persist="false"]'
    });
});
```

and restoring the form to a working situation was possible by:

```js
$(function() {
    $('#orderInfoForm').garlic();
});
```

We now see that the form is emptied, but that the form submit works. I think the form should not be emptied, but only the storage should be emptied right?

**Comment by rvanlaak** [comment]
@guillaumepotier I now found out that data is not even submitted at all. Any idea why `1.3.0` is not working for us?

**Comment by rvanlaak** [comment]
FYI: I can now confirm that cherry-picking #105 on top of tag `1.2.4` resolves all issues. 

We will start using this one in production: https://github.com/rvanlaak/Garlic.js/tree/pre-events

So there is some regression in the standard behavior since `1.3.0`.

**Comment by guillaumepotier** [comment]
Hi @rvanlaak 

I do not understand the problem here. I do not recall Garlic emptying values ever on a form. It just fills values with what it has in storage. Clearing/Emptying fields is really weird.

Could you provide a jsbin/jsfidle etc.. to show that behavior with latest release please?

Thanks

**Comment by cmer** [comment]
I'm having the same issue.

**Comment by AlexeyKosov** [comment]
Ran into the same bug, had to revert to `1.2.4`

**Comment by chamnap** [comment]
Facing the same issue. It's wierd. The textboxes contains the value, but the empty data got sent.

**Comment by chamnap** [comment]
@guillaumepotier, it's on this line, https://github.com/guillaumepotier/Garlic.js/blob/master/garlic.js#L118. Is it a typo or what? With this line of code, it will empty all inputs on submit....

**Comment by rvanlaak** [comment]
@guillaumepotier what about merging #105 to resolve this? 👍

**Comment by turgs** [comment]
So, it looks to me like #105 has been merged in, which from the comments above, suggest it may resolve this issue.

It doesn't. The issue still exists for me. Even if I remove all my garlicjs configuration options, and just call `$('form').garlic()` on the form, I still experience this problem. I'm using Firefox 58.

**Comment by turgs** [comment]
I've got it working. I agree with @chamnap that the error is on this line https://github.com/guillaumepotier/Garlic.js/blob/master/garlic.js#L118

I changed it from
`$( this.parentForm ).on( 'submit reset' , false, $.proxy( this.remove, this ) );`
to
`$( this.parentForm ).on( 'submit reset' , false, $.proxy( this.destroy, this ) );`
...and that fixed it for me.

**Comment by msanatan** [comment]
Confirming with @turgs and @chamnap, changing that line fixes the error

**Comment by guillaumepotier** [comment]
Ok guys, seems to be a nasty typo here.

Would you please submit a fix PR then?

Best

**Comment by Soullivaneuh** [comment]
Please see https://github.com/guillaumepotier/Garlic.js/pull/116
