### ISSUE TITLE
Garlic.js throws exception when in private mode for safari

### ISSUE THREAD

**Issue by sarchak** [guillaumepotier/Garlic.js#90]
Garlic.js throws exception when in private mode on safari. We should access localstorage in a try catch block.

http://stackoverflow.com/questions/21159301/quotaexceedederror-dom-exception-22-an-attempt-was-made-to-add-something-to-st

**Comment by guillaumepotier** [comment]
Yes that's right.

I should definitely rely on https://github.com/Wisembly/basil.js we developed later that handles properly all user storages subtilities and would avoid this bug.

**Comment by sttema** [comment]
@guillaumepotier, @sarchak, please take a look at https://github.com/guillaumepotier/Garlic.js/pull/95
